### ISSUE TITLE
EX30: Button "stop climatization" doesn't work

### ISSUE THREAD

**Issue by arboeh** [thomasddn/ha-volvo-cars#10]
### The problem
The button "stop climatization" does'nt work ans throws an error.

### Additional information
Works in Volvo EX30 app

### API availability
What does the `API status` sensor report:

* [X] OK
* [ ] Something else (please clarify): 
* [ ] N/A

### Diagnostics
```
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 07:58:42 (3 Vorkommnisse)
Zuletzt protokolliert: 08:20:13

[140070886185648] Unexpected exception
[140070524262656] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volvo_cars/volvo/api.py", line 210, in _async_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://api.volvocars.com/connected-vehicle/v2/vehicles/**REDACTED**/commands/climatization-stop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/volvo_cars/button.py", line 120, in async_press
    result = await self.coordinator.api.async_execute_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.entity_description.api_command
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/volvo_cars/volvo/api.py", line 147, in async_execute_command
    body = await self._async_post(_API_CONNECTED_ENDPOINT, f"commands/{command}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/volvo/api.py", line 175, in _async_post
    return await self._async_request(hdrs.METH_POST, endpoint, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volvo_cars/volvo/api.py", line 220, in _async_request
    raise VolvoApiException from ex
custom_components.volvo_cars.volvo.models.VolvoApiException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/volvo_cars/button.py", line 139, in async_press
    raise HomeAssistantError from ex
homeassistant.exceptions.HomeAssistantError
```

**Comment by thomasddn** [comment]
This one is a little weird, so a few questions:

1. What is the status of the "Car connection" sensor?
2. Does start climatization work?
3. Does stopping it always throw an error?

My car is in an underground parking at the moment, so I can't test.

**Comment by arboeh** [comment]
> This one is a little weird, so a few questions:
> 
> 1. What is the status of the "Car connection" sensor?
> 2. Does start climatization work?
> 3. Does stopping it always throw an error?
> 
> My car is in an underground parking at the moment, so I can't test.

1. available
2. start works and is shown as "on" in app
3. same error while running and trying to stop then, stopping only possible in app

**Comment by thomasddn** [comment]
Could you give it a go with the new beta (b1)?

If it is still not working, then please do the following:

- Enable debug logging
- Press "Start climatization"
- Press "Stop climatization"
- Disable debug logging
- Attach the log file to this issue (be sure to redact VIN number from the exception messages)

**Comment by arboeh** [comment]
I have to check this later at home.

**Comment by arboeh** [comment]
```
2024-12-22 18:44:05.841 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-stop executing
2024-12-22 18:44:05.841 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop]: POST https://api.volvocars.com/connected-vehicle/v2/vehicles/**REDACTED**/commands/climatization-stop
2024-12-22 18:44:06.822 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop] status: 500
2024-12-22 18:44:06.823 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop] body: {'error': {'message': 'INTERNAL_SERVER_ERROR', 'description': 'Error returned from car'}}
2024-12-22 18:44:06.823 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop] error: Internal Server Error
2024-12-22 18:44:06.823 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-stop error
2024-12-22 18:44:06.823 ERROR (MainThread) [homeassistant.helpers.script.ex30_climatization] ex30_climatization: Error executing script. Error for call_service at pos 1: 
2024-12-22 18:44:06.824 ERROR (MainThread) [homeassistant.components.automation.info_auto_klimatisierung_auto_aus] [INFO - AUTO]: Klimatisierung Auto aus: Error executing script. Error for call_service at pos 1: 
2024-12-22 18:44:06.826 ERROR (MainThread) [homeassistant.components.automation.info_auto_klimatisierung_auto_aus] Error while executing automation automation.info_auto_klimatisierung_auto_aus: 
```

**Comment by thomasddn** [comment]
I see you run this from an automation. Are you sure the car is not in use while you perform the climatization-stop command? The status of the `Car connection` sensor should be `available`.

**Comment by thomasddn** [comment]
To be honest, I think it's an issue with the Volvo API. I've asked in [the Volvo Cars thread on the HA community](https://community.home-assistant.io/t/volvo-cars-integration/796417/52?u=thomas_be) if someone else with an EX30 can confirm this behavior.

**Comment by rononline** [comment]
I have the same "problem"

```
[140280634962512] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volvo_cars/volvo/api.py", line 210, in _async_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://api.volvocars.com/connected-vehicle/v2/vehicles/*************/commands/climatization-stop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/volvo_cars/button.py", line 121, in async_press
    result = await self.coordinator.api.async_execute_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.entity_description.api_command
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
```

**Comment by thomasddn** [comment]
> I have the same "problem"

Also for an EX30?

**Comment by rononline** [comment]
Ow yes, also an EX30.

**Comment by thomasddn** [comment]
So it's safe to assume it's something specific to the EX30 that isn’t handled well by the Volvo API. 

I’ll send an email to Volvo after the holidays, because I don’t want it to be buried under a ton of other emails. But don’t get your hopes up because I’ve sent them an email before and I didn’t get any response so far.

**Comment by lieven121** [comment]
Works on the XC40 BEV

I was wondering
Is it possible to see the state in the integration?

**Comment by thomasddn** [comment]
> Is it possible to see the state in the integration?

No, weird as it is, but the Volvo API does not return that information (although the Volvo app has some way to show it).

**Comment by thomasddn** [comment]
@ChanceStad I have a XC40 MY2024 fully electric and see the same issue. However, it used to work before, I'm absolutely sure of that. The weird thing is that the API call seems to succeed, so I guess it must be something at Volvo's end.

```
2025-06-04 12:17:56.293 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-start executing
2025-06-04 12:17:56.293 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-start]: POST https://api.volvocars.com/connected-vehicle/v2/vehicles/**REDACTED**/commands/climatization-start
2025-06-04 12:17:58.522 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-start] status: 200
2025-06-04 12:17:58.522 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-start] response: {'data': {'vin': '**REDACTED**', 'invokeStatus': 'COMPLETED', 'message': ''}}
2025-06-04 12:17:58.522 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-start result: COMPLETED

2025-06-04 12:18:13.951 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-stop executing
2025-06-04 12:18:13.951 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop]: POST https://api.volvocars.com/connected-vehicle/v2/vehicles/**REDACTED**/commands/climatization-stop
2025-06-04 12:18:17.141 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop] status: 200
2025-06-04 12:18:17.141 DEBUG (MainThread) [custom_components.volvo_cars.volvo.api] Request [commands/climatization-stop] response: {'data': {'vin': '**REDACTED**', 'invokeStatus': 'COMPLETED', 'message': ''}}
2025-06-04 12:18:17.142 DEBUG (MainThread) [custom_components.volvo_cars.button] Command climatization-stop result: COMPLETED
```
