### ISSUE TITLE
Exception reported in logs occasionally 

### ISSUE THREAD

**Issue by billraff** [thomasddn/ha-volvo-cars#4]
### The problem
<!-- 
  It appears that my vehicle while out and about reports as unavailable. Seems ‘unavailable’ is not listed as an option so exception appears in the log:

Logger: homeassistant
Source: components/sensor/__init__.py:651
First occurred: 9:54:51 AM (8 occurrences)
Last logged: 12:07:06 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/volvo_cars/entity.py", line 82, in _handle_coordinator_update
    super()._handle_coordinator_update()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 651, in state
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Sensor sensor.volvo_xc90_availability provides state value 'unavailable', which is not in the list of options provided

-->


### Additional information
<!-- 
  Provide additional information, if any.
-->


### API availability
<!-- 
  Place an 'x' between the brackets to indicate your answer.
-->
What does the `API status` sensor report:

* [ ] OK
* [ ] Something else (please clarify): 
* [ ] N/A

### Diagnostics
<!-- 
  If you think it is applicable, download the diagnostics and attach it to this issue. Privacy related data is redacted. To not disclose your setup, you may delete everything but the data element.
-->

**Comment by billraff** [comment]
Will re-submit once at my computer.
