### ISSUE TITLE
Central lock doesn't work

### ISSUE THREAD

**Issue by arboeh** [thomasddn/ha-volvo-cars#9]
### The problem
The central lock sensor doesn't work.

### Additional information
Works in Volvo EX30 App.
Maybe permission issue due to unlock..? Volvo App want's additional security confirmation, like fingerprint.

### API availability
What does the `API status` sensor report:

* [X] OK
* [ ] Something else (please clarify): 
* [ ] N/A

### Diagnostics
```
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 07:46:44 (1 Vorkommnisse)
Zuletzt protokolliert: 07:46:44

[140070886194144] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 239, in async_handle_unlock_service
    await self.async_unlock(**self.add_default_code(kwargs))
  File "/config/custom_components/volvo_cars/lock.py", line 92, in async_unlock
    await self._async_handle_command(self.entity_description.unlock_command, False)
  File "/config/custom_components/volvo_cars/lock.py", line 125, in _async_handle_command
    raise HomeAssistantError(
    ...<7 lines>...
    )
homeassistant.exceptions.HomeAssistantError: Failed to unlock vehichle. Status: completed. Message: RDU_2_1_1_0_0
```

**Comment by thomasddn** [comment]
Oh, that one is on me! I'll fix it.

**Comment by thomasddn** [comment]
Can you try the new beta version please? If it works, I'll release it as stable.

**Comment by arboeh** [comment]
Sorry, still the same error.
![Screenshot_20241219-170248](https://github.com/user-attachments/assets/553dc6bc-0d17-4e2c-8c60-deaf5f408853)

**Comment by thomasddn** [comment]
As mentioned in the other issue, I released a dummy yesterday. Could you try with the new beta please?
